export const findAll = async () =>{
    try {
        return 'llegamo hasta aca';
    } catch (error) {
        console.error(error);
    }
}